#!/usr/bin/env bash
# Idempotent Cloud Agent bootstrap for the IntentIQ / VesperWise Next.js app.
# Installs dependencies and creates a keyless local-dev .env.local when one is
# absent. Real credentials injected as Cloud Agent Secrets (process env vars)
# take precedence over these placeholders, since Next.js does not override
# already-defined environment variables with .env file values.
set -euo pipefail

cd "$(dirname "$0")/.."

echo "[cloud-agent-install] Installing npm dependencies..."
npm install --no-audit --no-fund

if [ ! -f .env.local ]; then
  echo "[cloud-agent-install] Creating keyless dev .env.local..."
  cat > .env.local <<'EOF'
# Keyless local-dev defaults generated by scripts/cloud-agent-install.sh.
# Uses deterministic mock signals; no external API keys required to run the app.
# Provide real values via Cloud Agent Secrets to enable full functionality.

MOCK_SIGNALS=true

SCORING_V2_ENABLED=true
SCORING_V3_ENABLED=false
SCORING_V3_SHADOW_ENABLED=false

# Clerk keys intentionally unset. In development @clerk/nextjs runs in "keyless
# mode", auto-provisioning a temporary dev instance so the app renders in a
# browser without any account. Provide real keys via Cloud Agent Secrets to use
# a claimed instance (process env vars take precedence over this file).

# Supabase / OpenRouter / Upstash left unset in keyless dev.
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=
OPENROUTER_API_KEY=
UPSTASH_REDIS_REST_URL=
UPSTASH_REDIS_REST_TOKEN=

# Worker shadow modes (safe defaults).
SCRAPLING_SHADOW_MODE=true
SCRAPLING_BROWSER_ENABLED=false
WEB_ENRICHMENT_SHADOW_MODE=true
WEB_ENRICHMENT_FUNDING_FALLBACK=false
EOF
else
  echo "[cloud-agent-install] .env.local already present; leaving it unchanged."
fi

echo "[cloud-agent-install] Done."
